config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :categories, shallow: true do
    resources :posts, shallow: true do
      resources :post_images, only: :destroy
      resources :comments, shallow: true
    end
  end

  root "categories#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  has_many :post_images, dependent: :destroy, as: :post_imageble, inverse_of: :post_imageble
  accepts_nested_attributes_for :post_images

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_post, only: :create
  before_action :set_comment, only: [:destroy, :edit, :update]

  authorize_resource

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to post_path(@comment.post)
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, post_images_attributes: [:image])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.slim
- if comment.body.present?
  .bl_wdth-70
    div class="comment_#{comment.id}"
      div class="card border-danger mb-3 block_shadow"
        div class="card-body text-danger"
          p class="card-text"
            = comment.body
            - if comment.post_images.present? && comment.post_images.last.image.attached?
              p Images:
              - comment.post_images.each do |post_image|
                - if post_image.image.attached?
                  div class="post_image_#{post_image.id}" style="float: left; padding: 5px"
                    = image_tag(post_image.image, style: 'height: 300px; width: auto;')
                    br
                    / - if can_destroy?(post_image)
                    /   = link_to 'delete image', post_image_path(post_image), method: :delete, remote: true, class: "btn btn-outline-danger btn-sm"
              br
        - if can?(:update, comment)
          div class="card-footer bg-danger comment_mth"
            = link_to "Change your comment", edit_comment_path(comment)
            '
            = link_to "Delete comment", comment_path(comment), method: :delete, remote: true
    / br

app/views/comments/create.js.erb
<% if @comment.persisted? %>
  $(".comment_zone").prepend('<%= j render @comment %>');
<% end %>

app/views/comments/destroy.js.erb
<% if @comment.destroyed? %>
  $(".comment_<%= @comment.id %>").remove();
<% end %>

app/views/comments/edit.html.slim
= link_to "Back to post page", post_path(@comment.post), class: "btn btn-outline-danger"
br

- if @comment.post_images.present? && @comment.post_images.last.image.attached?
  p Images:
  - @comment.post_images.each do |post_image|
    div class="post_image_#{post_image.id}"
      = image_tag(post_image.image, style: 'height: 300px; width: auto;')
      br
      - if can_destroy?(post_image)
        = link_to 'delete image', post_image_path(post_image), method: :delete, remote: true, class: "btn btn-outline-danger btn-sm"
  br

br
= form_with model: @comment, local: true do |f|
  = f.label :body, "Change your comment"
  br
  = f.text_area :body, requred: true, class: "form-control bl_wdth-70"
  p Images:
  .add-images
    = render "posts/nested_files/add_image_field", f: f
    = link_to_add_association 'Add file', f, :post_images,
            partial: "posts/nested_files/nested_image_field",
            class: 'btn btn-outline-dark btn-sm'
  br
  = f.submit class: "btn btn-danger", style: "margin-top: 5px"