config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :categories, shallow: true do
    resources :posts, shallow: true do
      resources :post_images, only: :destroy
      resources :comments, shallow: true
    end
  end

  root "categories#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :post_images, dependent: :destroy, as: :post_imageble, inverse_of: :post_imageble
  accepts_nested_attributes_for :post_images

  validates :title, :body, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_category, only: [:new, :create]

  authorize_resource

  def show
    @comments = @post.comments.order(created_at: :desc)
    @comment = @post.comments.new
    @comment.post_images.new
  end

  def new
    @post = @category.posts.new
    @post.post_images.new
  end

  def create
    @post = @category.posts.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    if @post.destroyed?
      redirect_to category_path(@post.category)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, post_images_attributes: [:image])
  end

  def set_category
    @category = Category.find(params[:category_id])
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/helpers/posts_helper.rb
module PostsHelper
  def str_coll
    ["first", "second", "last"]
  end
end

app/views/posts/_form.html.slim
div class="bl_wdth-50"
  = form_with model: [@category, @post], local: true do |f|
    = render "shared/errors", resource: @post
    br
    = f.text_field :title, class: "form-control"
    = f.label :title
    br
    = f.text_area :body, class: "form-control"
    = f.label :body
    br
    p Images:
    .add-images
      / = render "posts/nested_files/add_image_field", f: f
      = link_to_add_association 'Add file', f, :post_images,
              partial: "posts/nested_files/nested_image_field",
              class: 'btn btn-outline-dark btn-sm'
    br
    / = f.select :something, options_for_select(str_coll), {}, class: "form-control"
    / br
    = f.submit class: "btn btn-danger btn-sm"

br

app/views/posts/edit.html.slim
= link_to 'Cancel', category_path(@post.category), class: 'btn btn-outline-danger'

br
br

h1= "Edit post #{@post.title}"

- if @post.post_images.present? && @post.post_images.last.image.attached?
  p Images:
  - @post.post_images.each do |post_image|
    div class="post_image_#{post_image.id}"
      = image_tag(post_image.image, style: 'height: 300px; width: auto;')
      br
      - if can_destroy?(post_image)
        = link_to 'delete image', post_image_path(post_image), method: :delete, remote: true, class: "btn btn-outline-danger btn-sm"
  br

= render "form"

app/views/posts/new.html.slim
= link_to 'Cancel', category_path(@category), class: 'btn btn-outline-danger'

br
br

h1 Create a new post

= render "form"

app/views/posts/show.html.slim
= link_to "Back to posts of category", category_path(@post.category), class: "btn btn-outline-danger btn-sm"

h1= @post.title

- if @post.user.avatar.attached?
  = image_tag(@post.user.avatar, class: "rounded-circle", style: "height: 30px; width: 30px")
'
= @post.body

- if @post.post_images.present? && @post.post_images.last.image.attached?
  p Images:
  - @post.post_images.each do |post_image|
    div class="post_image_#{post_image.id}"
      = image_tag(post_image.image, style: 'height: 300px; width: auto;')
      br
      / - if can_destroy?(post_image)
      /   = link_to 'delete image', post_image_path(post_image), method: :delete, remote: true, class: "btn btn-outline-danger btn-sm"
  br

.post_mth
  - if can?(:destroy, @post)
    = link_to "Edit", edit_post_path(@post)
    '
    = link_to "Delete", post_path(@post), method: :delete

.add_comment
  div class="card border-dark bl_wdth-70"
    div class="card-body bg-danger"
      - if can?(:create, Comment)
        div class="new_comment bl_wdth-70"
          = form_with model: [@post, @comment] do |f|
            = f.label :body, 'Add your comment'
            br
            = f.text_area :body, required: true, class: "form-control"
            p Images:
            .add-images
              / = render "posts/nested_files/add_image_field", f: f
              = link_to_add_association 'Add file', f, :post_images,
                      partial: "posts/nested_files/nested_image_field",
                      class: 'btn btn-outline-dark btn-sm'
            br
            = f.submit class: "btn btn-outline-dark btn-sm", style: "margin-top: 5px"
        br
br
.comment_zone
  = render @comments