config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :categories, shallow: true do
    resources :posts, shallow: true do
      resources :post_images, only: :destroy
      resources :comments, shallow: true
    end
  end

  root "categories#index"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :nullify

  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  authorize_resource

  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all.order(name: :asc)
  end

  def show
    @posts = @category.posts.order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    if @category.destroyed?
      redirect_to categories_path
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.slim
.col-4
  div class="category_#{category.id}"
    .category_card
      .row
        .col-7
          = link_to category.name, category_path(category)
        .col
          - if can?(:update, category)
            = link_to "Edit", edit_category_path(category)
            '
            span |
            '
            = link_to "Delete", category_path(category), method: :delete
    br

app/views/categories/_form.html.slim
= form_with model: @category, local: true do |f|
  = render "shared/errors", resource: @category
  br
  = f.label :name
  br
  = f.text_field :name, class: "form-control", style: "width: 50%"
  br
  = f.submit class: "btn btn-danger"

app/views/categories/edit.html.slim
h1= "Edit category #{@category.name}"
= render "form"

app/views/categories/index.html.slim
- if can?(:create, Category)
  = link_to "Add new category", new_category_path, class: "btn btn-outline-danger"

h1 Categories
.row
  = render @categories

app/views/categories/new.html.slim
h1 Create a new category
= render "form"

app/views/categories/show.html.slim
h3
  = link_to "Back to categories list", categories_path, class: "btn btn-outline-danger btn-sm"
  '
  - if can?(:create, Post)
    = link_to "New post", new_category_post_path(@category), class: 'btn btn-outline-danger btn-sm'

h1= "Posts of Category #{@category.name}"

- @posts.each do |post|
  .post_mth
    .post_card
      = link_to post.title, post_path(post)
    br